Generación de archivo final de asistentes
PyBAQ/sar pull request #12
Opened 2020-04-21 03:36 UTC by bgarcia92

# **Pull request**
Close #6 

## Observaciones
Se agrega función de generación de archivo final de asistentes en excel

2020-04-21 17:12 UTC, pyjavo requested changes
Las tablas no son congruentes en datos por lo que el resultado de la generación de archivos no se puede verificar. Por ejemplo este caso:

En el archivo de Google Forms existe un usuario registrado como **John Galindo** con email gerontologia@angostura-antioquia.gov.co mientras que en el Archivo de prueba de Meetup el usuario asociado al mismo correo se llama **John Zea**.

Parece que el resultado al final es una mezcla de ambas filas o ignoró el registro de John Zea.

Favor corregir

2020-04-21 19:24 UTC, bgarcia92 commented
@javierdaza en este issue solo se contempla la generación del archivo (copiando el dataframe del archivo de Google) y deje en el comentario que se debe reemplazar el dataframe resultante del análisis y consolidación de registros

2020-04-21 21:03 UTC, pyjavo approved these changes

2020-04-21 21:03 UTC, merged

2020-12-15 22:08 UTC, carasen12 approved these changes
a4cb10f2b39b6e3b84944758e43896aed30e3996