Lectura de archivo de asistentes de Meetup
PyBAQ/sar pull request #8
Opened 2020-04-17 03:34 UTC by bgarcia92

# **Pull request**
---
Issue #2 

### **Observaciones**
---
Se realiza lectura de archivo basado en parámetros de archivo de configuración

2020-04-17 14:01 UTC, pyjavo requested changes
@bgarcia92 Se ve bien. Solo 2 sugerencias:
1. El archivo de .gitignore deberia ignorar la carpeta de settings de vscode
2. Eliminar el archivo de .vscode/settings.json del PR
3. Llamemos a los archivos en minuscula (File.py a file.py) 

La lógica se ve bien

2020-04-17 16:10 UTC, bgarcia92 commented
@javierdaza el settings.json tiene los parámetros que recibe el script para cargar los datos y que se modifica para que el tema sea configurable, que opinas?

2020-04-17 17:28 UTC, javierdaza commented
@bgarcia92 no parece una buena práctica. ¿Si quiero correr el código desde un servidor o usando otro editor como vim, sublime, etc.. entonces no funcionaría el script?

2020-04-17 17:31 UTC, javierdaza commented
"venv\\Scripts\\python.exe" esta apuntando a un .exe. ¿Si estoy desde linux tampoco me funcionaría?

2020-04-17 22:12 UTC, bgarcia92 commented
@javierdaza el archivo settings.json no tiene ninguna key o accesos a cuentas, en este primer alcance se pensó en tener un script local por lo que es necesario el archivo de configuración. La otra forma que  vi para hacerlo, es tomando variables del SO o de una instancia pero cualquiera no podría correrlo. 

> "venv\Scripts\python.exe" esta apuntando a un .exe. ¿Si estoy desde linux tampoco me funcionaría?
Este es mi venv, con el cambio que no he subido ya no estaría en el repo.

2020-04-17 22:24 UTC, javierdaza commented
A bueno. Pero no importa que cualquiera no pueda correrlo. La idea es usarlo solo nosotros para logística.
Me preocupa es que así como está ahora solo funcionaría en una máquina windows y no todos usamos windows.
¿Qué opinas?

2020-04-17 22:30 UTC, bgarcia92 commented
Lo puedes correr en cualquier máquina, solo me toca agregar las carpetas del venv y de vscode en el .gitignore, si quieres actualizo y lo validas... debería funcionarte sin problemas

2020-04-17 22:31 UTC, javierdaza commented
Dale. Revisaré
venv ya está en el .gitignore si usaste el que viene por defecto para los proyectos de python

2020-04-17 22:34 UTC, javierdaza commented
@bgarcia92 bro, no borres lo que viene en el .gitignore. Eso está bien.

Solo añade .vscode/ al final

2020-04-20 16:11 UTC, pyjavo requested changes
@bgarcia92 El archivo requirements debe ser generado con el comando:

`pip freeze > requirements.txt`

y debe lucir mas o menos así:
```
numpy==1.18.3
pandas==1.0.3
python-dateutil==2.8.1
pytz==2019.3
six==1.14.0
xlrd==1.2.0
```

2020-04-20 16:30 UTC, pyjavo approved these changes

2020-04-20 16:30 UTC, merged